export type GovernedToolResolution = { destructive: boolean; registered: boolean };

export const governedTools: Record<string, { destructive: boolean }> = {
	bash: { destructive: true },
	edit: { destructive: true },
	write: { destructive: true },
	read: { destructive: false },
	grep: { destructive: false },
	find: { destructive: false },
	ls: { destructive: false },
	her_status: { destructive: false },
	her_recall: { destructive: false },
	her_session_list: { destructive: false },
	her_session_read: { destructive: false },
	her_session_search: { destructive: false },
	// Writes into the memory store, can trigger a paid wake, and puts text into
	// another agent's system prompt — the same side-effect family as
	// her_task_continue, not the read-only family. Cedar is deny-by-default for
	// destructive tools, so this ships denied until Fei grants a named permit
	// (the her_task_spawn / _stop / _continue precedent in her-trust.cedar).
	her_session_send: { destructive: true },
	her_feedback: { destructive: false },
	her_sync: { destructive: false },
	her_task_create: { destructive: false },
	her_task_update: { destructive: false },
	her_task_list: { destructive: false },
	her_task_spawn: { destructive: true },
	her_task_continue: { destructive: true },
	her_task_stop: { destructive: true },
	her_task_output: { destructive: false },
	her_bg_task_list: { destructive: false },
	her_publish: { destructive: true },
	her_privacy_audit: { destructive: false },
	her_privacy_check: { destructive: false },
	her_memory_retract: { destructive: false },
	her_cost_report: { destructive: false },
	her_telegram_queue: { destructive: false },
	her_proposal_record: { destructive: false },
	her_proposal_feedback: { destructive: false },
	her_proposal_stats: { destructive: false },
	her_proposal_list: { destructive: false },
	her_goal_start: { destructive: false },
	her_goal_next: { destructive: false },
	her_goal_checkpoint: { destructive: false },
	her_goal_complete: { destructive: false },
	her_goal_list: { destructive: false },
	her_synthesize_choice_model: { destructive: false },
	her_synthesize_self_narrative: { destructive: false },
	her_review_context: { destructive: false },
	her_review_verify: { destructive: false },
	her_keep: { destructive: false },
	her_revert: { destructive: false },
	her_remember: { destructive: false },
	her_world_note: { destructive: false },
	her_intake_source: { destructive: false },
	her_intake_path: { destructive: false },
	her_bootstrap_feed: { destructive: false },
	her_zone_note: { destructive: false },
	her_taste_judgment: { destructive: false },
	her_idea: { destructive: false },
	her_judgment: { destructive: false },
	her_memory_status: { destructive: false },
	her_hands_snapshot: { destructive: false },
	her_hands_act: { destructive: false },
	preview_open_review: { destructive: false },
	browser_navigate: { destructive: false },
	browser_read_page: { destructive: false },
	browser_act: { destructive: false },
	artifact_publish: { destructive: true },
	her_show_widget: { destructive: false },
	her_ui_act: { destructive: false },
	her_act: { destructive: false },
	her_upsert_relay_provider: { destructive: false },
	her_convert: { destructive: false },
	her_ocr: { destructive: false },
	her_archive: { destructive: false },
	her_imgmin: { destructive: false },
	her_pdf: { destructive: false },
	her_mcp_list: { destructive: false },
	her_mcp_call: { destructive: false },
};

export function resolveGovernedTool(name: string): GovernedToolResolution {
	const tool = governedTools[name];
	if (!tool) return { destructive: true, registered: false };
	return { destructive: tool.destructive, registered: true };
}
