import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import type { ExtensionAPI, ToolDefinition } from "@earendil-works/pi-coding-agent";
import { governedTools } from "../src/lib/governed-tools.ts";
import { type DesignSystemDeps, registerDesignSystemTools } from "../src/preview/design-system.ts";

const ISO = "2026-09-04T12:00:00.000Z";
const HEAD = "abc123def";
const SOURCE = "../samantha-ui/src/app/globals.css";
const DISCIPLINE =
	"These are the values the product actually ships. Design with them — do not invent a colour, radius or easing. If you need a role that does not exist yet, say why it must exist before you add it.";

const FIXTURE = `/* Gallery tokens. */
:root {
	/* ink */
	--background: #FFFFFF;
	--accent: #2F6F4E;
}
.dark {
	--background: #0B0B0B;
	--glow: #C2A878;
}
`;

const EXPECTED_MD = `# samantha-ui design system

Source: ${SOURCE} @ ${HEAD}
Loaded: ${ISO}

/* Gallery tokens. */

| token | light | dark |
| --- | --- | --- |
| --background | #FFFFFF | #0B0B0B |
| --accent | #2F6F4E | — |
| --glow | — | #C2A878 |
`;

const EXPECTED_CSS = `/* Generated by design_system_load from ${SOURCE} @ ${HEAD} at ${ISO}. Do not hand-edit. */
:root {
	--background: #FFFFFF;
	--accent: #2F6F4E;
}
.dark {
	--background: #0B0B0B;
	--glow: #C2A878;
}
`;

function harness(deps: DesignSystemDeps): Map<string, ToolDefinition> {
	const tools = new Map<string, ToolDefinition>();
	const pi = {
		registerTool(tool: ToolDefinition) {
			tools.set(tool.name, tool);
		},
	} as unknown as ExtensionAPI;
	registerDesignSystemTools(pi, deps);
	return tools;
}

async function run(tool: ToolDefinition | undefined, params: Record<string, unknown>) {
	assert.ok(tool);
	const result = (await tool.execute("call-1", params, undefined, undefined, undefined as never)) as {
		content: Array<{ type: string; text: string }>;
		details?: Record<string, unknown>;
	};
	return { text: result.content.map((part) => part.text).join("\n"), details: result.details ?? {} };
}

async function tempRoot(t: test.TestContext): Promise<string> {
	const dir = await mkdtemp(join(tmpdir(), "her-design-system-"));
	t.after(() => rm(dir, { recursive: true, force: true }));
	return dir;
}

function stubDeps(root: string, overrides: Partial<DesignSystemDeps> = {}): DesignSystemDeps {
	return {
		repoRoot: root,
		now: () => ISO,
		headOf: async () => HEAD,
		readSource: async () => FIXTURE,
		...overrides,
	};
}

function wroteNothing(root: string): void {
	assert.equal(existsSync(join(root, "design", "system")), false);
	assert.equal(existsSync(join(root, "packages", "design-lab", "src", "tokens", "product.css")), false);
}

test("unknown target refuses and lists the known targets, writing nothing", async (t) => {
	const root = await tempRoot(t);
	const tools = harness(stubDeps(root));
	const { text, details } = await run(tools.get("design_system_load"), { target: "nope" });

	assert.equal(details.ok, false);
	assert.match(text, /samantha-ui/);
	wroteNothing(root);
});

test("missing css refuses and writes nothing", async (t) => {
	const root = await tempRoot(t);
	const tools = harness(
		stubDeps(root, {
			readSource: async () => {
				throw Object.assign(new Error("ENOENT: no such file"), { code: "ENOENT" });
			},
		}),
	);
	const { text, details } = await run(tools.get("design_system_load"), { target: "samantha-ui" });

	assert.equal(details.ok, false);
	assert.match(text, /samantha-ui/);
	assert.match(text, /globals\.css/);
	wroteNothing(root);
});

test("light without dark refuses as a half set, writing nothing", async (t) => {
	const root = await tempRoot(t);
	const tools = harness(
		stubDeps(root, {
			readSource: async () => `:root {\n\t--background: #FFFFFF;\n}\n`,
		}),
	);
	const { text, details } = await run(tools.get("design_system_load"), { target: "samantha-ui" });

	assert.equal(details.ok, false);
	assert.match(text, /1/);
	assert.match(text, /0/);
	assert.match(text, /半套主题不是一个设计系统/);
	wroteNothing(root);
});

test("a full load writes four artifacts whose token values match the fixture byte for byte", async (t) => {
	const root = await tempRoot(t);
	const tools = harness(stubDeps(root));
	const { text, details } = await run(tools.get("design_system_load"), { target: "samantha-ui" });

	assert.equal(details.ok, true);
	assert.match(text, /design\/system\/samantha-ui\/tokens\.md/);
	assert.match(text, /design\/system\/samantha-ui\/tokens\.css/);
	assert.match(text, /design\/system\/samantha-ui\/receipt\.json/);
	assert.match(text, /packages\/design-lab\/src\/tokens\/product\.css/);
	assert.match(text, new RegExp(DISCIPLINE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));

	const md = await readFile(join(root, "design", "system", "samantha-ui", "tokens.md"), "utf8");
	const css = await readFile(join(root, "design", "system", "samantha-ui", "tokens.css"), "utf8");
	const product = await readFile(join(root, "packages", "design-lab", "src", "tokens", "product.css"), "utf8");
	assert.equal(md, EXPECTED_MD);
	assert.equal(css, EXPECTED_CSS);
	assert.equal(product, css);
});

test("receipt.json records the source head and token counts that were actually loaded", async (t) => {
	const root = await tempRoot(t);
	const tools = harness(stubDeps(root));
	await run(tools.get("design_system_load"), { target: "samantha-ui" });

	const receipt = JSON.parse(
		await readFile(join(root, "design", "system", "samantha-ui", "receipt.json"), "utf8"),
	) as {
		target: string;
		sourcePath: string;
		sourceHead: string | null;
		loadedAt: string;
		tokenCount: { light: number; dark: number };
	};
	assert.equal(receipt.target, "samantha-ui");
	assert.equal(receipt.sourcePath, SOURCE);
	assert.equal(receipt.sourceHead, HEAD);
	assert.equal(receipt.loadedAt, ISO);
	assert.deepEqual(receipt.tokenCount, { light: 2, dark: 2 });
});

test("a token that exists only in dark shows an em dash on the light side", async (t) => {
	const root = await tempRoot(t);
	const tools = harness(stubDeps(root));
	await run(tools.get("design_system_load"), { target: "samantha-ui" });

	const md = await readFile(join(root, "design", "system", "samantha-ui", "tokens.md"), "utf8");
	assert.match(md, /\| --glow \| — \| #C2A878 \|/);
});

test("design_system_load is registered as a governed non-destructive tool", () => {
	assert.equal(governedTools.design_system_load?.destructive, false);
});

// The paragraph a product writes above its own token block IS the design system;
// the values below it are only numbers. A real globals.css starts with @import
// lines, so "comment at the top of the file" would miss it entirely.
test("the doc comment sitting above the light selector is carried across, even behind a preamble", async (t) => {
	const root = await tempRoot(t);
	const preambled = `@import "tailwindcss";\n@custom-variant dark (&:is(.dark *));\n\n/* One accent, carried by content and state, never by chrome. */\n${FIXTURE.slice(FIXTURE.indexOf(":root"))}`;
	const tools = harness({
		repoRoot: root,
		now: () => ISO,
		headOf: async () => HEAD,
		readSource: async () => preambled,
	});
	const { details } = await run(tools.get("design_system_load"), {});
	assert.equal(details.ok, true);
	const md = await readFile(join(root, "design/system/samantha-ui/tokens.md"), "utf8");
	assert.match(md, /One accent, carried by content and state, never by chrome\./);
});

// A shipped stylesheet wraps long values (shadows, gradients) across lines, and
// on Windows those lines end in CRLF. Carried through verbatim they put a raw
// newline inside a markdown table cell, which snaps the row in half — she would
// read shredded values for exactly the tokens that are hardest to guess.
test("a value wrapped across lines is folded onto one line, in both the table and the css", async (t) => {
	const root = await tempRoot(t);
	const wrapped =
		"/* doc */\r\n:root {\r\n\t--shadow: 0 1px 2px rgba(0,0,0,0.04),\r\n\t\t0 12px 32px rgba(0,0,0,0.08);\r\n}\r\n.dark {\r\n\t--shadow: none;\r\n}\r\n";
	const tools = harness({
		repoRoot: root,
		now: () => ISO,
		headOf: async () => HEAD,
		readSource: async () => wrapped,
	});
	const { details } = await run(tools.get("design_system_load"), {});
	assert.equal(details.ok, true);

	const md = await readFile(join(root, "design/system/samantha-ui/tokens.md"), "utf8");
	const rows = md.split("\n").filter((line) => line.startsWith("| --") && !line.startsWith("| --- |"));
	assert.equal(rows.length, 1, `expected one table row, got:\n${rows.join("\n")}`);
	assert.equal(rows[0], "| --shadow | 0 1px 2px rgba(0,0,0,0.04), 0 12px 32px rgba(0,0,0,0.08) | none |");

	const css = await readFile(join(root, "design/system/samantha-ui/tokens.css"), "utf8");
	assert.ok(!css.includes("\r"), "generated css must not carry CR from the source");
	assert.ok(!md.includes("\r"), "generated markdown must not carry CR from the source");
});
